//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaLesson07DF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtaSinhVien
    {
        public string PtaMaSV { get; set; }
        public string PtaTenSV { get; set; }
        public string PtaPhone { get; set; }
        public string PtaEmail { get; set; }
        public Nullable<bool> PtaPhai { get; set; }
        public string PtaMaKH { get; set; }
    }
}
