//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaK22CNT4LS10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtaAccount
    {
        public int PtaID { get; set; }
        public string PtaUserName { get; set; }
        public string PtaPassword { get; set; }
        public string PtaFullName { get; set; }
        public string PtaEmail { get; set; }
        public string PtaPhone { get; set; }
        public Nullable<bool> PtaActive { get; set; }
    }
}
