//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaOnTap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhanTruongAnh_2210900087Entities : DbContext
    {
        public PhanTruongAnh_2210900087Entities()
            : base("name=PhanTruongAnh_2210900087Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pta_Sach> Pta_Sach { get; set; }
        public virtual DbSet<PtaTacGia> PtaTacGias { get; set; }
    }
}
