//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaOnTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pta_Sach
    {
        public string Pta_MaSach { get; set; }
        public string Pta_TenSach { get; set; }
        public Nullable<int> Pta_SoTrang { get; set; }
        public Nullable<int> Pta_NamXB { get; set; }
        public string Pta_MaTG { get; set; }
        public Nullable<bool> Pta_TrangThai { get; set; }
    
        public virtual PtaTacGia PtaTacGia { get; set; }
    }
}
