//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaOnTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtaTacGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PtaTacGia()
        {
            this.Pta_Sach = new HashSet<Pta_Sach>();
        }
    
        public string Pta_MaTG { get; set; }
        public string Pta_TenTG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pta_Sach> Pta_Sach { get; set; }
    }
}
