//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaK22CNT4Lesson11Db.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PtaK22CNT4Lessson11DbEntities : DbContext
    {
        public PtaK22CNT4Lessson11DbEntities()
            : base("name=PtaK22CNT4Lessson11DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PtaCategory> PtaCategories { get; set; }
        public virtual DbSet<PtaProduct> PtaProducts { get; set; }
    }
}
