//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaK22CNT4Lesson11Db.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PtaCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PtaCategory()
        {
            this.PtaProducts = new HashSet<PtaProduct>();
        }
        [Display(Name = "Mã Danh M?c")]
        public int PtaID { get; set; }
        [Display(Name = "Tên danh m?c")]

        public string PtaCateName { get; set; }
        [Display(Name = "Tr?ng thái")]

        public Nullable<bool> PtaStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PtaProduct> PtaProducts { get; set; }
    }
}
