//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaK22CNT4Lesson11Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtaProduct
    {
        public string PtaID2210900087 { get; set; }
        public string PtaProName { get; set; }
        public Nullable<int> PtaQty { get; set; }
        public Nullable<double> PtaPrice { get; set; }
        public Nullable<int> PtaCateId { get; set; }
        public Nullable<bool> PtaActive { get; set; }
    
        public virtual PtaCategory PtaCategory { get; set; }
    }
}
